site_name: My Japanese book
site_description: A notebook to take notes of my japanese course.
repo_url: https://github.com/charlstown/my-japanese-book
site_author: charlstown

# Configuration
# Theme
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.indexes
  language: ja

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


# Sorting menu pages
nav:
    - Home: 'index.md'
    - Book:
        - 'book/index.md' # getting started
        - Alfabetos: 'book/alfabetos.md'


# Extensions
markdown_extensions:
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: ja
  - markdownextradata

# css
extra_css:
  - assets/stylesheets/extra.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js

# Copyright message
copyright: Copyright &copy; My Japanese book - 2024

# Global variables
extra:
  links:
    self-host: 'url'
    learning-host: 'url'
